### ISSUE TITLE
Geen lang

### ISSUE THREAD

**Issue by elina2022** [adfrontend/fdnd.nl#12]
HTML element bevat geen lang kenmerk

**Comment by elina2022** [comment]
![image](https://user-images.githubusercontent.com/112861148/197487934-3aac2b1a-8491-4c80-80f3-694fa6f66ff8.png)

**Comment by KoopReynders** [comment]
cannot fix. Staat er wel ... Zie ook code van de HTML hier op GitHub 
https://github.com/fdnd/fdnd.nl/blob/source/index.html
