### ISSUE TITLE
Update de images

### ISSUE THREAD

**Issue by Siem-P** [adfrontend/fdnd.nl#13]
De images op de Fdnd.nl website zijn verouderd. Het lijkt mij leuk om foto's van de nieuwe locatie te zien, omdat dit wel een bijzondere locatie is. 

@KoopReynders Misschien ook leuk om even wat foto's te maken van èèn of meerdere WeLoveWeb sessie('s) en op de website plaatsen.

Ik heb een paar foto's uitgekozen die denk ik wel leuk zijn om er op te zetten.

| <img src="https://user-images.githubusercontent.com/64197688/197496420-52e4160c-9fb2-4221-af86-73ed6b37c5c5.JPG" width="500"> | <img src="https://user-images.githubusercontent.com/64197688/197497335-e7878b3e-213d-4651-acb8-0c71ff1ba9c0.JPG" width="500"> |
 | :--: | :--: |

| <img src="https://user-images.githubusercontent.com/64197688/197497537-31c71c25-2ed7-4d0d-813c-ce4adbf9276e.JPG" width="400"> |
| :--: |

**Comment by cydstumpel** [comment]
Heuuu, lekkere foto's Siem, ik ga ze in mijn archief knallen en misschien voor Insta gebruiken! THANKS
