### ISSUE TITLE
html lang lijkt niet goed te staan

### ISSUE THREAD

**Issue by KoopReynders** [adfrontend/fdnd.nl#14]
https://github.com/fdnd/fdnd.nl/blob/2a8c46a1b88e17c501ce4c375085d610c0ee108b/index.html#L2

De language setting op het `HTML` element staat op `lang=nl`, maar de website is in het engels. 

Misschien beter de taal op engels zetten? Dat is o.a. beter voor screen-readers. 

Hier kun je meer lezen over het lang attribuut https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/lang

**Comment by cydstumpel** [comment]
Gefixed ✨ in https://github.com/fdnd/fdnd.nl/commit/52ad3eeb8e695a1af031ad750c19bf8bab5d1c10
